parameters:
#    pa_t_earth.example.class: PaT\EarthBundle\Example

services:
#    pa_t_earth.example:
#        class: %pa_t_earth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
