parameters:
#    pa_t_user.example.class: PaT\UserBundle\Example

services:
#    pa_t_user.example:
#        class: %pa_t_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
